=== gavrilo97/projekat/validacija.dtd
<!ELEMENT proizvodi (proizvod+)>
<!ELEMENT proizvod (kategorija,cena,brand,artikal,akcija)>
<!ELEMENT kategorija(#PCDATA)>
<!ELEMENT cena(#PCDATA)>
<!ELEMENT artikal(#PCDATA)>
<!ELEMENT tagovi(tag+)>
<!ELEMENT tag(#PCDATA)>
<!ELEMENT akcija(#PCDATA)>

<!ATTLIST cena valuta (dinar|evro) "dinar">
<!ATTLIST akcija popustCena (EMPTY|CDATA) #IMPLIED>
<!ATTLIST akcija datumIsteka (EMPTY|CDATA) #IMPLIED>

=== gavrilo97/projekat/proizvodi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proizvodi SYSTEM "validacija.dtd">
<proizvodi xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="xsdval.xsd">
    <proizvod>
        <kategorija>Desktop racunari</kategorija>
        <cena valuta="dinar"></cena>
        <artikal></artikal>
        <tagovi>
            <tag></tag>
        </tagovi>
        <akcija popustCena="" datumIsteka="" ></akcija>
    </proizvod>
</proizvodi>
